# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='chat',
        ),
    ]
